### ISSUE TITLE
Si imagen será borrada por el WebCrawler de Cooltext.com favor de poner "link de recomendacion" para protegerla.

### ISSUE THREAD

**Issue by IoTeacher** [SoyBastidasGit/SoyBastidasGit#1]
![Screen Shot 2021-02-25 at 9 54 39 PM](https://user-images.githubusercontent.com/2523851/109262569-a0c5c180-77b6-11eb-96e7-7942d3089d71.png)

Una vez que las corrija lo solicitado tendrá el:

![](https://images-na.ssl-images-amazon.com/images/I/41mUvRO4kXL.jpg)

**Comment by SoyBastidasGit** [comment]
link de recomendación de cooltext añadido
